import Head from 'next/head'
import Layout from '@/components/Layout'
import Image from 'next/image'
import profilePic from "../../public/images/profile/digibrain.png";
import AnimatedText from '@/components/AnimatedText'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        
      </Head>
      <main className='flex items-center text-dark w-full min-h-screenn'>
        <Layout className='pt-0'>

          <div className="flex items-center justify-between w-full">
            <div className='w-1/2'>
              <Image src={profilePic} alt="CodeBucks" className='w-full h-auto rounded-full' />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center'>
              <AnimatedText text="Championing Cutting-Edge Web Development and Driving Innovation." className='!text-6xl !text-left'/>
              <p>
              Highly skilled Full Stack Web Developer
              with expertise in frontend development.
              Proficient in JavaScript (ES6+), React.js,
              Next.js, Svelte, and WordPress. Strong
              understanding of HTML5, CSS3, and
              responsive design principles. Experienced
              in building dynamic and user-friendly web
              applications using modern web
              development frameworks and tools. <br />
              Possesses knowledge of backend
              technologies such as Node.js, Express.js,
              MongoDb and SQL databases.
              Collaborative team player with a passion
              for creating exceptional user experiences.
              Seeking a mid-senior level web developer
              role to contribute to the development of
              innovative and impactful web solutions.
              </p>
            </div>
          </div>
        </Layout>
      </main>
    </>
  )
}
